// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoiQOx1MBNXA6GJEYAV7frLNh5sKzLAX0',
    appId: '1:126164867804:web:34663371984fb2588cb219',
    messagingSenderId: '126164867804',
    projectId: 'hypha-wallet',
    authDomain: 'hypha-wallet.firebaseapp.com',
    storageBucket: 'hypha-wallet.appspot.com',
    measurementId: 'G-V3TB144HGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI-0GhFAg43uzTSjHeqHu_MwhMiVZlYFQ',
    appId: '1:126164867804:android:adb47790cb9c5e5e8cb219',
    messagingSenderId: '126164867804',
    projectId: 'hypha-wallet',
    storageBucket: 'hypha-wallet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFScEE-zGnyH8qSeVg7Mc8a_43d3afb9M',
    appId: '1:126164867804:ios:45c86504011b40978cb219',
    messagingSenderId: '126164867804',
    projectId: 'hypha-wallet',
    storageBucket: 'hypha-wallet.appspot.com',
    iosClientId: '126164867804-3p032sqv8ri6r63482kt38pfun5kb460.apps.googleusercontent.com',
    iosBundleId: 'earth.hypha.wallet.hyphaWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFScEE-zGnyH8qSeVg7Mc8a_43d3afb9M',
    appId: '1:126164867804:ios:45c86504011b40978cb219',
    messagingSenderId: '126164867804',
    projectId: 'hypha-wallet',
    storageBucket: 'hypha-wallet.appspot.com',
    iosClientId: '126164867804-3p032sqv8ri6r63482kt38pfun5kb460.apps.googleusercontent.com',
    iosBundleId: 'earth.hypha.wallet.hyphaWallet',
  );
}
