/// Flutter icons HyphaIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HyphaIcons
///      fonts:
///       - asset: fonts/HyphaIcons.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class HyphaIcons {
  HyphaIcons._();

  static const _kFontFam = 'HyphaIcons';
  static const String? _kFontPkg = null;

  static const IconData cancel_circled = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar_sign = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subtraction_1 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onboarding_key = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history_b = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_svgrepo_com = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_b = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_b = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_b = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_b = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
